FROM node:14.13.1-alpine3.10

WORKDIR /app

# Install dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .

EXPOSE 8080

ENV HOST "0.0.0.0"

# Start command
CMD ["npm", "start"]