version: '3.5'
services:
    front:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - ${PORT}:${PORT}
        volumes:
            - /app/node_modules
            - .:/app
        env_file:
            - .env
