version: '3.5'
services:
    front:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
        env_file:
            - .env
    bing:
        build:
            context: ./infraBing
        ports:
            - 3000:80
